extends:
  - '@bangbang93/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  project: tsconfig.eslint.json
rules:
  '@typescript-eslint/no-magic-numbers': off
  '@typescript-eslint/no-unused-vars': off
