extends:
  - '@bangbang93/recommended'
  - prettier
parser: '@typescript-eslint/parser'
plugins:
  - prettier
parserOptions:
  project: tsconfig.eslint.json
rules:
  '@typescript-eslint/no-magic-numbers': off
  '@typescript-eslint/no-unused-vars': off
  prettier/prettier: error
